---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
    pandoc_args: [
        "+RTS", "-K64m",
        "-RTS"
        ]
---


## Loading and preprocessing the data
```{r echo = TRUE}
#Zip file is always present into project directory
dataZipFile <- "activity.zip"
dataFile <- "activity.csv"

#Check if exists unzipped, else unzip it
if(!file.exists(dataFile)) unzip(dataFile)

#Read file
basedata <- read.csv(dataFile)

#Remove NAs
data <- basedata[!is.na(basedata$steps),]
```


## What is mean total number of steps taken per day?
```{r echo = TRUE}
library(dplyr)

#Calculate Total Steps per day
dataStepsSum <- with(data, aggregate(steps, list(date), sum))
dataStepsSum <- rename(dataStepsSum, date = Group.1, steps = x)
dataStepsSum <- select(dataStepsSum, steps, date)

#Calculate mean and median rounded to 2 decimals
meanSteps <- round(mean(dataStepsSum$steps),2)
medianSteps <- round(median(dataStepsSum$steps),2)
medianSteps

#Generate graph
hist(dataStepsSum$steps, breaks = nrow(dataStepsSum))
abline(v = meanSteps, col = "red")
abline(v = medianSteps, col = "blue")
```

.      | values
------ | ----------------
mean   | `r as.character(meanSteps)`
median | `r as.character(medianSteps)`


## What is the average daily activity pattern?

```{r echo = TRUE}
library(ggplot2)

dataIntervalAverage <- with(data, aggregate(steps, list(interval), mean))
dataIntervalAverage <- rename(dataIntervalAverage, interval = Group.1, steps = x)
with(dataIntervalAverage, qplot(x = interval, y = steps, geom = "line"))
maxIntervalAverage <- dataIntervalAverage[dataIntervalAverage$steps == max(dataIntervalAverage$steps),]
```

The maximum average interval of 5-minutes is the interval `r maxIntervalAverage[1]` with an average of `r round(maxIntervalAverage[2],2)` steps.


## Imputing missing values

```{r echo = TRUE}
#Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
naRows <- nrow(basedata[is.na(basedata),])
naRows

#Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
```

I'm going to use the mean for that 5-minute interval with na value for steps

```{r echo = TRUE}
#Create a new dataset that is equal to the original dataset but with the missing data filled in.

dataToTreat <- basedata

dataToTreat %>% 
inner_join(dataIntervalAverage, by = "interval") %>%
mutate(steps = ifelse(is.na(steps.x), steps.y, steps.x)) %>%
select(steps, date, interval) -> dataTreated

#Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

#Calculate Total Steps per day
dataStepsSum <- with(dataTreated, aggregate(steps, list(date), sum))
dataStepsSum <- rename(dataStepsSum, date = Group.1, steps = x)
dataStepsSum <- select(dataStepsSum, steps, date)

#Calculate mean and median rounded to 2 decimals
meanStepsTreated <- round(mean(dataStepsSum$steps),2)
medianStepsTreated <- round(median(dataStepsSum$steps),2)
medianStepsTreated

#Generate graph
hist(dataStepsSum$steps, breaks = nrow(dataStepsSum))
abline(v = meanStepsTreated, col = "red")
abline(v = medianStepsTreated, col = "blue")
```

values | data with NA    | data without NA
------ | --------------- | ---------------
mean   | `r as.character(meanSteps)`   | `r as.character(meanStepsTreated)`
median | `r as.character(medianSteps)` | `r as.character(medianStepsTreated)`

## Are there differences in activity patterns between weekdays and weekends?

```{r echo = FALSE}
library(lubridate)

getTypeOfDay <- function(x) {ifelse(x %in% c(7,1),"Weekends", "Weekdays")}

data %>% 
         mutate(wdays = wday(ymd(date))) %>% 
         mutate(typeOfDay = as.factor(getTypeOfDay(wdays))) %>%
         select(steps, date, interval, typeOfDay) -> dataDays

g <- ggplot(dataDays, aes(interval, steps)) 
g <- g + geom_line(col="blue") + facet_wrap(~typeOfDay)
g <- g + ggtitle("Comparative of activity patterns between weekdays and weekends")
g

```

